### ISSUE TITLE
Demo example is broken

### ISSUE THREAD

**Issue by Botnary** [KidkArolis/cherrytree-redux-react-example#1]
Demo example is broken and throws a fatal there. http://kidkarolis.github.io/cherrytree-redux-react-example

**Comment by KidkArolis** [comment]
Hi, could you give me more details, which browser, what's the error + stack trace?
It works for me :-S

**Comment by Botnary** [comment]
Browser: Google Chrome 44.0.2403.155 (64-bit)

```
TypeError: e.routes.find is not a function
    at Array.<anonymous> (app.min.js:21)
    at t (app.min.js:22)
    at app.min.js:22
    at k (app.min.js:29)
    at S (app.min.js:29)
    at app.min.js:29
    at MutationObserver.y (app.min.js:29)
```

**Comment by KidkArolis** [comment]
Thanks again for reporting. I've included `babel/polyfill` and stopedp using `Object.assign` in `cherrytree-for-react@1.0.1` now. Should be working on older browsers.
